# Generated by Django 3.2.7 on 2021-09-30 14:14

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
