# Generated by Django 3.2.7 on 2021-10-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='stars',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
