# Generated by Django 3.2.7 on 2021-10-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20211007_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
